[book]
authors = ["MayaData"]
language = "en"
multilingual = false
src = "."
title = "MayaData Culture"

[build]
create-missing = false

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/mayadata-io/culture"
additional-css = ["css/open-in.css"]
cname = "culture.mayadata.io"
